import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api'
@Injectable({
  providedIn: 'root'
})
export class DataService implements InMemoryDbService {

  constructor() { }
  createDb() {

    let phones = [
      { id: 1, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 2, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 3, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 4, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 5, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 6, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 7, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 8, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 9, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 10, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 11, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 12, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 13, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 14, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 15, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },

      { id: 16, marque: 'Xiaomi', modele: "MI-8-lite", refrence: "Xia-mi-8-l", prix: "820", dateFinPromo: '', OS: "android", taille: "6.5", pross: "snapdragon 660", ram: "4go", rom: "64 go", grantie: "2 ans", Etat: "hot", quantité: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", empreinte: "arriére", nbreSim: "2", batt: "3350 mAh", face: "oui" },
      { id: 17, marque: 'Huawaei', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 18, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 19, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 20, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 21, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 22, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 23, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 24, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 25, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 26, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 27, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 28, marque: 'Xiaomi', modele: "MI-8-lite", refrence: "Xia-mi-8-l", prix: "820", dateFinPromo: '', OS: "android", taille: "6.5", pross: "snapdragon 660", ram: "4go", rom: "64 go", grantie: "2 ans", Etat: "hot", quantité: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", empreinte: "arriére", nbreSim: "2", batt: "3350 mAh", face: "oui" },
      { id: 29, marque: 'Huawaei', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 30, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 31, marque: 'Xiaomi', modele: "MI-8-lite", refrence: "Xia-mi-8-l", prix: "820", dateFinPromo: '', OS: "android", taille: "6.5", pross: "snapdragon 660", ram: "4go", rom: "64 go", grantie: "2 ans", Etat: "hot", quantité: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", empreinte: "arriére", nbreSim: "2", batt: "3350 mAh", face: "oui" },
      { id: 32, marque: 'Huawaei', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 33, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 34, marque: 'Xiaomi', modele: "MI-8-lite", refrence: "Xia-mi-8-l", prix: "820", dateFinPromo: '', OS: "android", taille: "6.5", pross: "snapdragon 660", ram: "4go", rom: "64 go", grantie: "2 ans", Etat: "hot", quantité: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", empreinte: "arriére", nbreSim: "2", batt: "3350 mAh", face: "oui" },
      { id: 35, marque: 'Huawaei', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 36, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" },
      { id: 37, marque: 'Xiaomi', modele: "MI-8-lite", refrence: "Xia-mi-8-l", prix: "820", dateFinPromo: '', OS: "android", taille: "6.5", pross: "snapdragon 660", ram: "4go", rom: "64 go", grantie: "2 ans", Etat: "hot", quantité: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", empreinte: "arriére", nbreSim: "2", batt: "3350 mAh", face: "oui" },
      { id: 38, marque: 'Huawaei', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 39, marque: 'Apple', modele: "Y8S", refrence: "BU-HU-Y8S-noir", prix: "3649", dateFinPromo: '', OS: "android 9", taille: "6.5", pross: "kirin 710 ", ram: "4 go", rom: "64 go", grantie: "1 an", Etat: "", quantité: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", empreinte: "arriére", nbreSim: "2", batt: "4000 Mah", face: "non" },
      { id: 40, marque: 'samsung', modele: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", prix: "7199", dateFinPromo: '15-12-2020', OS: "android 10", taille: "7.6 Amoled pliable X2", pross: "snapdragon 865+", ram: "12 go", rom: "256 go", grantie: "5 ans", Etat: "new", quantité: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", empreinte: "sous ecran", nbreSim: "2", batt: "4500 mAh x2", face: "oui" }
    ];

    return { phones };
  }
}