import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api'
@Injectable({
  providedIn: 'root'
})
export class DataService implements InMemoryDbService {

  constructor() { }
  createDb() {

    let phones = [
      { id: 1, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "30% OFF", stock: "0", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 2, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 3, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 4, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 5, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 6, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 7, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 8, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 9, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 10, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 11, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 12, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 13, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 14, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 15, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },

      { id: 16, brand: 'Xiaomi', model: "MI-8-lite", refrence: "Xia-mi-8-l", price: "820", dateEndSale: '', os: "android", size: "6.5", cpu: "snapdragon 660", ram: "4go", rom: "64 go", waranty: "2 ans", status: "hot", stock: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", fingerPrint: "arriére", sim: "2", battery: "3350 mAh", faceId: "oui" },
      { id: 17, brand: 'Huawaei', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 18, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 19, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 20, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 21, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 22, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 23, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 24, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 25, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 26, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 27, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 28, brand: 'Xiaomi', model: "MI-8-lite", refrence: "Xia-mi-8-l", price: "820", dateEndSale: '', os: "android", size: "6.5", cpu: "snapdragon 660", ram: "4go", rom: "64 go", waranty: "2 ans", status: "hot", stock: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", fingerPrint: "arriére", sim: "2", battery: "3350 mAh", faceId: "oui" },
      { id: 29, brand: 'Huawaei', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 30, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 31, brand: 'Xiaomi', model: "MI-8-lite", refrence: "Xia-mi-8-l", price: "820", dateEndSale: '', os: "android", size: "6.5", cpu: "snapdragon 660", ram: "4go", rom: "64 go", waranty: "2 ans", status: "hot", stock: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", fingerPrint: "arriére", sim: "2", battery: "3350 mAh", faceId: "oui" },
      { id: 32, brand: 'Huawaei', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 33, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 34, brand: 'Xiaomi', model: "MI-8-lite", refrence: "Xia-mi-8-l", price: "820", dateEndSale: '', os: "android", size: "6.5", cpu: "snapdragon 660", ram: "4go", rom: "64 go", waranty: "2 ans", status: "hot", stock: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", fingerPrint: "arriére", sim: "2", battery: "3350 mAh", faceId: "oui" },
      { id: 35, brand: 'Huawaei', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 36, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" },
      { id: 37, brand: 'Xiaomi', model: "MI-8-lite", refrence: "Xia-mi-8-l", price: "820", dateEndSale: '', os: "android", size: "6.5", cpu: "snapdragon 660", ram: "4go", rom: "64 go", waranty: "2 ans", status: "hot", stock: 50, color: ["blue", "rouge", "noir"], frontCam: "13 MP", backCam: "24 MP", fingerPrint: "arriére", sim: "2", battery: "3350 mAh", faceId: "oui" },
      { id: 38, brand: 'Huawaei', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 39, brand: 'Apple', model: "Y8S", refrence: "BU-HU-Y8S-noir", price: "3649", dateEndSale: '', os: "android 9", size: "6.5", cpu: "kirin 710 ", ram: "4 go", rom: "64 go", waranty: "1 an", status: "", stock: 100, color: ["noir", "vert"], frontCam: "8 MP + 2 MP", backCam: "48 MP + 2MP", fingerPrint: "arriére", sim: "2", battery: "4000 Mah", faceId: "non" },
      { id: 40, brand: 'samsung', model: "z Fold 2 Noir", refrence: "SM-ZF0LD2-BK", price: "7199", dateEndSale: '15-12-2020', os: "android 10", size: "7.6 Amoled pliable X2", cpu: "snapdragon 865+", ram: "12 go", rom: "256 go", waranty: "5 ans", status: "new", stock: "1", color: ["noir", "vert", "orange"], frontCam: "10 MP", backCam: "12 MP + 12 MP + 12 MP", fingerPrint: "sous écran", sim: "2", battery: "4500 mAh x2", faceId: "oui" }
    ];

    return { phones };
  }
}